[package]
name = 'zoomerjoin'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'zoomerjoin'

[dependencies]
extendr-api = {version ="0.3.1", features =["ndarray"]}
fxhash = "0.2.1"
itertools = "0.10.5"
ndarray = {version ="0.15.6", features = ["rayon"]}
ndarray-rand = "0.14.0"
rand = "0.8.5"
rayon = "1.6.1"
smallvec = "1.10.0"
